name: 'Publish Allure Report'
id: upload-allure
description: 'Uploads an Allure report to the central report host'
inputs:
  serverUrl:
    description: 'API endpoint for report upload'
    required: true
  serverApiKey:
    description: 'API key for authentication'
    required: true
  projectName:
    description: 'Project name'
    required: true
  branch:
    description: 'Branch name'
    required: true
  reportName:
    description: 'Report name'
    required: true
  reportType:
    description: 'Report type (allure/raw)'
    required: false
    default: 'allure'
  path:
    description: 'Path to allure-results or zip'
    required: true
  testResult:
    description: 'Test result exit code (0=success, nonzero=failure)'
    required: false 
  testsPassed:
    description: 'Number of passed tests'
    required: false
  testsFailed:
    description: 'Number of failed tests'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        bash ./scripts/publish-report.sh \
          --url "${{ inputs.serverUrl }}" \
          --key "${{ inputs.serverApiKey }}" \
          "${{ inputs.projectName }}" \
          "${{ inputs.branch }}" \
          "${{ inputs.reportName }}" \
          "${{ inputs.reportType }}" \
          "${{ inputs.path }}"
      shell: bash

    - name: Publish Allure Report
      timeout-minutes: 12
      continue-on-error: true
      env:
        API_SECRET:   ${{ secrets.API_KEY }}
        SERVER_URL:   ${{ vars.STAGING_SERVER_URL }}

      uses: sireto/allure-report-host@v1.2
      with:
        path: ./allure-results

    - name: Update Check Run with Allure Summary
      if: always()
      timeout-minutes: 2
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Try to find the check run for this job
        CHECK_RUN_ID=$(gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/check-runs?check_name=${GITHUB_JOB}" \
          --jq '.check_runs[] | select(.status == "in_progress" or .status == "queued") | .id' \
          | head -n 1 || echo "")
        if [[ -z "$CHECK_RUN_ID" ]]; then
          echo "::warning::Could not find active check run ID – skipping summary update"
          exit 0
        fi

        # Determine outcome
        UPLOAD_OUTCOME="${{ steps.upload-allure.outcome || 'timeout' }}"
        if [[ "$UPLOAD_OUTCOME" == "success" ]]; then
          STATE="success"
          STATUS_TEXT="Upload completed"
        elif [[ "$UPLOAD_OUTCOME" == "timeout" || "$UPLOAD_OUTCOME" == "failure" ]]; then
          STATE="timed_out"
          STATUS_TEXT="Upload timed out or failed"
        else
          STATE="neutral"
          STATUS_TEXT="Upload status unknown"
        fi

        SUMMARY="**Allure Report**\n\
        Status: $STATUS_TEXT\n\
        Passed: ${{ steps.run_tests.outputs.passed || 'unknown' }}\n\
        Failed: ${{ steps.run_tests.outputs.failed || 'unknown' }}\n\
        [View Report (if successful)](${{ vars.STAGING_SERVER_URL }}/${{ github.repository }}/${{ github.ref_name }}/${{ github.run_id }}/index.html)"

        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          "/repos/${GITHUB_REPOSITORY}/check-runs/$CHECK_RUN_ID" \
          -f "status=completed" \
          -f "conclusion=$STATE" \
          -f "output[title]=Allure Report" \
          -f "output[summary]=$SUMMARY" || echo "::warning::Failed to update check summary"
      shell: bash