name: Move v1 tag

on:
  push:
    tags:
      - 'v1.*'

permissions:
  contents: write
  
jobs:
  update-major-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Move v1 tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag -f v1
          git push origin v1 --force